export const BASE_URL = "http://localhost:3000";
export const skills = [
    "C",
    "C++",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "Go",
    "HTML",
    "CSS",
    "React",
    "Next.js",
    "Angular",
    "Vue.js",
    "Redux",
    "Tailwind CSS",
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "REST API",
    "GraphQL",
    "WebSockets",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Firebase",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Jenkins",
    "GitHub Actions",
    "Kafka",
    "RabbitMQ",
    "Jest",
    "Cypress",
    "Playwright",
    "Postman",
    "Linux",
    "Data Structures",
    "Algorithms",
    "OOP",
    "System Design",
    "Microservices",
    "JWT",
    "OAuth",
    "Machine Learning",
    "Artificial Intelligence"
];